# Generated by Django 5.2.17 on 2026-09-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('maternal_surname', models.CharField(blank=True, verbose_name='Apellido Materno')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('datebirth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('internal_number', models.CharField(max_length=120, verbose_name='Número interno')),
                ('external_number', models.CharField(max_length=120, verbose_name='Número externo')),
                ('postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('suburb', models.CharField(max_length=60, verbose_name='Delegación')),
                ('country', models.CharField(max_length=60, verbose_name='País')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts', verbose_name='Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='Número de tarjeta')),
                ('expiration', models.CharField(max_length=16, verbose_name='Fecha de expiración')),
                ('cvc', models.CharField(max_length=3, verbose_name='CVC')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts', verbose_name='Cuenta')),
            ],
        ),
    ]
