# Generated by Django 5.2.17 on 2026-09-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nombre')),
                ('image_url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('image_url', models.URLField(verbose_name='URL')),
                ('release_date', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('description', models.CharField(verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('promotion', models.FloatField(verbose_name='Promoción')),
                ('category', models.CharField(choices=[('controls', 'Controles'), ('consoles', 'Consolas'), ('accessories', 'Accesorios'), ('passes', 'Pases'), ('games', 'Juegos')], default='PENDING', verbose_name='Categoria')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.companies', verbose_name='Compañia')),
            ],
        ),
    ]
