# Generated by Django 5.2.17 on 2026-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('games', 'Juegos'), ('consoles', 'Consolas'), ('passes', 'Pases'), ('accessories', 'Accesorios'), ('controls', 'Controles')], default='PENDING', verbose_name='Categoria'),
        ),
    ]
