# Generated by Django 5.2.17 on 2026-09-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('games', 'Juegos'), ('controls', 'Controles'), ('consoles', 'Consolas'), ('accessories', 'Accesorios'), ('passes', 'Pases')], default='PENDING', verbose_name='Categoria'),
        ),
    ]
