# Generated by Django 5.2.17 on 2026-09-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('games', 'Juegos'), ('accessories', 'Accesorios'), ('consoles', 'Consolas'), ('passes', 'Pases'), ('controls', 'Controles')], default='PENDING', verbose_name='Categoria'),
        ),
    ]
