# Generated by Django 5.2.17 on 2026-09-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('controls', 'Controles'), ('games', 'Juegos'), ('passes', 'Pases'), ('accessories', 'Accesorios'), ('consoles', 'Consolas')], default='PENDING', verbose_name='Categoria'),
        ),
    ]
