# Generated by Django 5.2.17 on 2026-09-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('consoles', 'Consolas'), ('controls', 'Controles'), ('passes', 'Pases'), ('games', 'Juegos'), ('accessories', 'Accesorios')], default='PENDING', verbose_name='Categoria'),
        ),
    ]
