# Generated by Django 5.2.17 on 2026-09-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(verbose_name='Total de compra')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts', verbose_name='Cuenta')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Dirección de envio')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.creditcard', verbose_name='Método de Pago')),
            ],
        ),
    ]
