# Generated by Django 5.2.17 on 2026-09-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billings', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Cantidad')),
                ('total', models.FloatField(verbose_name='Total')),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.billing', verbose_name='Recibo')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Producto')),
            ],
        ),
    ]
