# Generated by Django 5.2.17 on 2026-09-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_billing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='billing_id',
            new_name='billing',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='product_id',
            new_name='product',
        ),
    ]
